frontend/src/components/integration/updatedAssessmentDisplay.tsx
frontend/src/components/integration/updatedTopicSelector.css
frontend/src/components/integration/updatedTopicSelector.tsx

Added the integration updation files of the frontend .

Added integration folder with UI updates

---

frontend/package-lock.json
frontend/package.json
frontend/public/graduation-cap.svg
frontend/src/App.css
frontend/src/App.tsx
frontend/src/components/AssessmentDisplay.css
frontend/src/components/Chatbot.css
frontend/src/components/ThemeToggle.tsx
frontend/src/components/TopicSelector.css
frontend/src/index.css
frontend/src/styles/ThemeToggle.css
frontend/src/utils/ThemeContext.tsx

- Implemented dark mode theme functionality across the application
- Fixed UI issues:
- Restored broken heading icon
- Improved chatbot interface to match original design
- Added ThemeToggle component
- Implemented ThemeContext for state management
- Updated styling in App and component-level CSS files
Please verify:
- Dark/Light mode toggle works correctly
- Heading icons display properly
- Chatbot UI matches the intended design

Dark Mode Implementation & UI Bug Fixes

---

team-chirag-semantic-analysis/backend/queryHandling/dynamic/ollama_dsa.py

added Dynamic query handling files with SERP API integration

Added files for dynamic query handling with Ollama and SERP API

---

project-beta/App.tsx
project-beta/FeatureHub.tsx

These are the folders from the app where I have made the major changes. Integrating them with models has to be done.

Ui work is done.

---

team-parthan-assessment/ai-quiz-generation/dsa.ts

Added AI Integration & Quiz Analysis module by Srishti Koni
This PR adds a new AI-powered quiz generator module under:
**Features:**
1. Topic-based MCQ quiz generation
2. Uses **Ollama (Mistral)** for offline AI model execution
3. Command-line interface using `readline` for interactive quiz
4. Score calculation and feedback based on correct answers
**Dependencies:**
1. Ollama– Local LLM backend  
2. Installed model: `mistral`  
3. Ollama version used: **Ollama v0.1.31** 
1. Start Ollama in background:
ollama run mistral

AI Integration & Quiz Analysis

---

README.md
client/src/components/Navbar.tsx
client/src/pages/HomePage.tsx

Made the dashboard naming standard for authenticated and non-authenticated users.

Standard Nmaing of buttons

---

team-nishita-dashboard/client/package-lock.json
team-nishita-dashboard/client/package.json
team-nishita-dashboard/client/src/App.tsx
team-nishita-dashboard/client/src/components/Home.tsx
team-nishita-dashboard/client/src/components/LandingPage.css
team-nishita-dashboard/client/src/components/LandingPage.tsx
team-nishita-dashboard/client/src/components/Login.tsx
team-nishita-dashboard/client/src/components/Navbar.tsx
team-nishita-dashboard/client/src/components/styles.css
team-nishita-dashboard/server/package-lock.json
team-nishita-dashboard/server/package.json

Landing page

---

team-chirag-semantic-analysis/frontend/package-lock.json
team-chirag-semantic-analysis/frontend/package.json
team-chirag-semantic-analysis/frontend/src/App.tsx
team-chirag-semantic-analysis/frontend/src/components/UserProfileMenu.tsx
team-chirag-semantic-analysis/frontend/src/contexts/ThemeContext.tsx
team-chirag-semantic-analysis/frontend/src/main.tsx
team-chirag-semantic-analysis/frontend/src/pages/Auth/Login.tsx
team-chirag-semantic-analysis/frontend/src/pages/Auth/Signup.tsx
team-chirag-semantic-analysis/frontend/src/pages/StudentView.tsx

Integrated a responsive and interactive student login/signup flow with real-time validation (field presence, format checks, password strength, confirmation match).
Added a user profile icon with dropdown in the top AppBar post-login to display student info.
Implemented a theme toggle (light/dark) beside the profile icon that applies across the entire app with a consistent UI experience.
Ensured routing and conditional rendering work correctly based on authentication state.

Added login/signup UI with theme toggle and user profile menu - By Aditi

---

team-nishita-dashboard/client/src/api/api.tsx
team-nishita-dashboard/client/src/components/Login.tsx
team-nishita-dashboard/client/src/components/Signup.tsx

added role feature

---

team-nishita-dashboard/client/package-lock.json
team-nishita-dashboard/client/package.json
team-nishita-dashboard/client/src/components/LandingPage.tsx

Toggle & Theme updation of Landing page.

UI-fixes-Landing-page

---

team-parthan-assessment/YouTube-Transcript/src/utils/transcriptViewer.ts

Create transcriptViewer.ts to view transcripts

---

team-parthan-assessment/YouTube-Transcript/src/utils/translate.ts

Translation is functional but not accurate yet; improvements planned

Created translate.ts

---

team-ayush-learningpath/frontend/src/components/DSAQuizEngine.tsx

- Added gamified features to the quiz interface.
- Suspicious activity detectors to prevent unfair means.
- Timer for each question for adding difficulty.

DSA Quiz Engine Interface 

---

team-parthan-assessment/ai-quiz-generation/Readme.md

This pull request adds a README.md file for the AI Quiz Generator module located in `team-parthan-assessment/ai-quiz-generation`.

odification of code and adding readme

---

README.md
backend/package-lock.json
backend/package.json
backend/src/index.ts
backend/src/models/User.ts
backend/src/routes/auth.ts
frontend/src/App.tsx
frontend/src/components/LoginPage.tsx
frontend/src/components/PrivateRoute.tsx
frontend/src/components/RegistrationPage.tsx

1. Built the backend Database to store user details
2. Created routes in express
3. Modified login and registration pages to connect to backend and store details
4. Working logout button
5. Restricted the dashboard page to only those who have logged in.

Completed working and encryption of login and registration pages

---

team-nishita-dashboard/client/src/components/AdminHome.tsx

Created Admin Home Page

---

team-ayush-learningpath/rs-engine/dataset/combined_data.csv

Added the synthetic dataset on which these models are trained.

Added the dataset

---

team-alakh-assessment/Server/package-lock.json
team-alakh-assessment/Server/package.json
team-alakh-assessment/client/index.html
team-alakh-assessment/client/package-lock.json
team-alakh-assessment/client/package.json
team-alakh-assessment/client/src/context/ThemeContext.tsx
team-alakh-assessment/client/src/context/ThemeProvider.tsx

Retained user's theme choice using localStorage
Fallback to system theme (prefers-color-scheme) when no stored preference is found

Added persistent theme support with system preference fallback

---

dsa-learning-app/src/components/Home.tsx
dsa-learning-app/src/components/Navbar.tsx
dsa-learning-app/src/i18n.ts
dsa-learning-app/src/translations.ts

Added the most widely used languages in India, these are accessed using drop down box in Navigation bar.

i18n translations in multiple languages added 

---

project-beta/App.js
project-beta/PasswordStrengthChecker.js

with strong password generation application.

Integarted the sign up page

---

team-parthan-assessment/backend/src/controllers/userDetailsController.ts
team-parthan-assessment/backend/src/routes/detailsRouter.ts
team-parthan-assessment/project-vansh/client/package-lock.json
team-parthan-assessment/project-vansh/client/package.json
team-parthan-assessment/project-vansh/client/src/components/MainPage.tsx
team-parthan-assessment/project-vansh/client/src/components/UserProfileDropdown.tsx
team-parthan-assessment/project-vansh/client/src/components/UserStats.tsx
team-parthan-assessment/project-vansh/client/src/interface/types.ts
team-parthan-assessment/project-vansh/client/src/services/detailService.ts

- Added server-side and frontend caching logic for the /me endpoint using SWR with deduping and revalidation control to optimize user profile data fetching.
- Created a backend endpoint '/api/me/update' to update the user's details.
- Integrated the update endpoint with the frontend via user dropdown interactions.
- Ensured consistency by triggering SWR mutate calls after updates to maintain cached data freshness.

Implemented caching for /me API and added endpoint for avgScore and masteredTopics update

---

team-alakh-assessment/client/src/App.tsx
team-alakh-assessment/client/src/pages/Dashboard.tsx
team-alakh-assessment/client/src/pages/Profile.tsx

Added styles and finalized profile component.

feat: Profile component

---

dsa-learning-app/package-lock.json
dsa-learning-app/package.json
dsa-learning-app/src/App.tsx
dsa-learning-app/src/components/DifficultySelection.tsx
dsa-learning-app/src/components/Home.tsx
dsa-learning-app/src/components/LanguageSelection.tsx
dsa-learning-app/src/components/Navbar.tsx
dsa-learning-app/src/components/Quiz.tsx
dsa-learning-app/src/components/QuizReview.tsx
dsa-learning-app/src/data/questions.ts
dsa-learning-app/src/index.css
dsa-learning-app/src/index.tsx
dsa-learning-app/src/main.tsx
dsa-learning-app/src/pages/NotFound.tsx
dsa-learning-app/src/styles/button.tsx
dsa-learning-app/src/styles/card.tsx

So here is the first quiz user must take after selecting his preferred programming language, that tests basic knowledge in basic syntax, datatypes, special features etc.

Basic Quiz on Programming Language choosen by user

---

package-lock.json
package.json
team-ayush-learningpath/backend/src/controllers/quizController.ts
team-ayush-learningpath/backend/src/routes/quiz.routes.ts
team-ayush-learningpath/backend/src/utils/graphUtils.ts

-added mastery score tracking via quiz result
-developed submission endpoint
-created initial recommendation algorithm for learning path.

Mastery score tracker

---

team-ayush-learningpath/Masterly/frontend/app/Admin/layout.tsx
team-ayush-learningpath/Masterly/frontend/app/Admin/page.tsx

Finalised the main page.tsx and layout.tsx pages for Admin portal

Finalised the Admin main page.tsx and layout.tsx

---

README.md
backend/package-lock.json
backend/package.json
backend/src/controllers/auth.ts
backend/src/models/User.ts
backend/src/routes/auth.ts
backend/src/utils/mailer.ts
frontend/src/App.tsx
frontend/src/components/ForgotPasswordModal.tsx
frontend/src/components/LoginPage.tsx
frontend/src/components/LogoutModal.css
frontend/src/components/PrivateRoute.tsx

Added a forgot password option on the login page.
When you select forgot password it:
1. Prompts you to enter your mail ID and checks if it is stored in the database. If not it generates an error
2. It send a 6 digit OTP to the mail ID which is valid for 10 minutes
3. If the entered OTP matches the OTP sent then it gives you the option to change the password after which you are redirected to the login page to login with your new password.

Added forgot password

---

team-parthan-assessment/backend/package-lock.json
team-parthan-assessment/backend/package.json
team-parthan-assessment/backend/src/controllers/authController.ts
team-parthan-assessment/backend/src/routes/authRoute.ts
team-parthan-assessment/backend/src/services/emailService.ts
team-parthan-assessment/project-vansh/client/src/App.tsx
team-parthan-assessment/project-vansh/client/src/auth/AuthComponent.tsx
team-parthan-assessment/project-vansh/client/src/auth/ForgotPassword.tsx
team-parthan-assessment/project-vansh/client/src/components/ResetPassword.tsx
team-parthan-assessment/project-vansh/client/src/services/authService.ts

NOTE: ADD EMAIL_USER and EMAIL_APP_PASS to env.

Implemented forgot password feature.

---

team-ayush-learningpath/Masterly/frontend/app/help/page.tsx

Here I have developed a contact support page that connects to the mail through formspree.
I also updated and modified the live chat bot

advances in the help page

---

team-ayush-learningpath/database/user.js

Added the user schema, this will act as blueprint.

Added user schema

---

team-nishita-dashboard/client/index.html
team-nishita-dashboard/client/src/contexts/ThemeContext.tsx

Chatbot integrated with team members Sonali, Deepali .

chatbot integrated globally

---

team-nishita-dashboard/client/.gitignore
team-nishita-dashboard/client/package-lock.json
team-nishita-dashboard/client/package.json
team-nishita-dashboard/client/src/App.tsx
team-nishita-dashboard/client/src/api/api.tsx
team-nishita-dashboard/client/src/components/AdminHome.tsx
team-nishita-dashboard/client/src/components/CoursePage.tsx
team-nishita-dashboard/client/src/components/UserHome.tsx
team-nishita-dashboard/client/src/contexts/AuthContext.tsx
team-nishita-dashboard/client/src/contexts/ProtectedRoute.tsx
team-nishita-dashboard/client/src/contexts/ThemeContext.tsx
team-nishita-dashboard/client/src/main.tsx
team-nishita-dashboard/client/src/styles/global.css
team-nishita-dashboard/client/src/utils/cloudinaryUpload.ts
team-nishita-dashboard/client/tsconfig.node.json
team-nishita-dashboard/server/index.ts
team-nishita-dashboard/server/models/course.ts
team-nishita-dashboard/server/package-lock.json
team-nishita-dashboard/server/package.json
team-nishita-dashboard/server/routes/course.ts

facility for admin to add courses with syllabus and materials via cloudinary

final file upload fixes

---

team-ayush-learningpath/Masterly/frontend/app/help-guide/page.tsx
team-ayush-learningpath/Masterly/frontend/app/help/page.tsx

This is the user guide page which gives basic idea about our application

Guide page

---

team-ayush-learningpath/database/course.js
team-ayush-learningpath/database/user-progress.js

This acts as blueprint for the documents to be inserted in "courses" collection.

Added the courses schema

---

team-nishita-dashboard/client/src/App.tsx
team-nishita-dashboard/client/src/components/AdminAnalytics.tsx
team-nishita-dashboard/client/src/components/AdminHome.tsx
team-nishita-dashboard/client/src/components/AdminLayout.tsx
team-nishita-dashboard/client/src/components/AdminMessages.tsx
team-nishita-dashboard/client/src/components/AdminReports.tsx
team-nishita-dashboard/client/src/components/AdminSidebar.tsx
team-nishita-dashboard/client/src/components/AdminSystemSettings.tsx
team-nishita-dashboard/client/src/components/AdminUserManagement.tsx
team-nishita-dashboard/client/src/components/Sidebar.tsx

Added Admin Sidebar

---

team-ayush-learningpath/Masterly/frontend/app/Admin/page.tsx
team-ayush-learningpath/Masterly/frontend/app/context/AuthContext.tsx
team-ayush-learningpath/Masterly/frontend/app/dashboard/page.tsx
team-ayush-learningpath/Masterly/frontend/app/learning-paths/page.tsx
team-ayush-learningpath/Masterly/frontend/app/profile/page.tsx
team-ayush-learningpath/Masterly/frontend/app/progress/page.tsx
team-ayush-learningpath/Masterly/frontend/components/DSAQuizEngine.tsx
team-ayush-learningpath/Masterly/frontend/hooks/useAuth.ts
team-ayush-learningpath/backend/src/controllers/userController.ts
team-ayush-learningpath/backend/src/models/userModel.ts
team-ayush-learningpath/backend/src/routes/userRoutes.ts
team-ayush-learningpath/backend/src/types/index.ts

- integrated full functional dashboard, progress, profile, and improved overall UI of the pages.

Final tested all unit modules

---

team-chirag-semantic-analysis/backend/DSA_VALIDATION_SUMMARY.md
team-chirag-semantic-analysis/backend/queryHandling/dsa_topic_validator.py
team-chirag-semantic-analysis/backend/queryHandling/dynamic/ollama_dsa_yt.py
team-chirag-semantic-analysis/backend/queryHandling/integrated_chat_handler.py
team-chirag-semantic-analysis/backend/queryHandling/learning_sessions.json
team-chirag-semantic-analysis/backend/queryHandling/test_dsa_integration.py
team-chirag-semantic-analysis/backend/queryHandling/unknown_queries.json
team-chirag-semantic-analysis/backend/test_api_dsa.py

- Add comprehensive DSA topic validator with keyword matching and semantic similarity
- Implement validation for 5 DSA categories: data structures, algorithms, complexity, techniques, problem types
- Integrate validation into chat handler to filter non-DSA queries

 Integrate NLP-based DSA topic validation system

---

team-nishita-dashboard/client/src/components/AdminSidebar.tsx
team-nishita-dashboard/client/src/components/Sidebar.styles.css
team-nishita-dashboard/client/src/components/Sidebar.tsx
team-nishita-dashboard/client/src/styles/global.css

Updated theme - Improved visibility of elements in light theme

fixed theme
